-- Unusable until https://github.com/sunjon/Shade.nvim/issues/7 gets fixed

-- require'shade'.setup({
--   overlay_opacity = 50,
--   opacity_step = 1,
--   keys = {
--     brightness_up    = '<Leader-Up>',
--     brightness_down  = '<Leader-Down>',
--     toggle           = '<Leader>s',
--   }
-- })
