#!/usr/bin/env bash

function openn {
  text_files=()
  image_files=()
  for f in "$@"; do
    case $(file -b --mime-type "$f") in
      text/*|application/json|inode/x-empty) text_files+=($(echo "$f" | sed "s/\ /\\\ /g"));;
      image/*) image_files+=("$f");;
      video/*) open -n "$f";;
      *) open "$f";;
    esac
  done
  (( ${#image_files[@]} )) && open "${image_files[@]}"
  if (( ${#text_files[@]} )); then
    filenames="$(echo ${text_files[@]})"
    alacritty --command bash -c "sleep .5 && $EDITOR $filenames"
  fi
}

export -f openn

alacritty --config-file "$(dirname $0)/fuzzy-opener.yml" \
          --title "floating" \
          --command bash -c 'printf "\e[5 q"; \
                             fzf --prompt="Open> " --multi --print0 | \
                             (nohup xargs -0 bash -c '\''openn "$@"'\'' \
                              _ &>/dev/null &)'
