#!/usr/bin/env bash

function openn {
  text_files=()
  image_files=()
  while read file; do
    case $(file -b --mime-type "$HOME/$file") in
      text/*|application/json|inode/x-empty)
        text_files+=($(echo "$HOME/$file" | sed "s/\ /\\\ /g"))
        ;;
      image/*)
        image_files+=("$file")
        ;;
      video/*)
        open -n "$file"
        ;;
      *)
        open "$file"
        ;;
    esac
  done
  (( ${#image_files[@]} )) && open "${image_files[@]}"
  if (( ${#text_files[@]} )); then
    filenames="$(echo ${text_files[@]})"
    alacritty -e sh -c "sleep .5 && $EDITOR $filenames"
  fi
}

(alacritty \
  --title 'fuzzy-opener' \
  --config-file "$HOME/.config/alacritty/fuzzy-opener.yml" \
  -e sh -c 'fzf --multi --height=10 --prompt="Open> " --border=horizontal >&3') 3>&1 \
  | openn
