#!/usr/bin/env bash

FILE="$1"

text_preview() {
  highlight -O ansi --force "$FILE"
}

pdf_preview() {
  pdftotext "$FILE" -
}

image_preview() {
  chafa --fill=block --symbols=block "$FILE"
}

video_preview() {
  mediainfo "$FILE"
}

audio_preview() {
  mediainfo "$FILE"
}

fallback_preview() {
  highlight -O ansi --force "$FILE"
}

case "$(file -b --mime-type $FILE)" in
  text/*) text_preview ;;
  */pdf) pdf_preview ;;
  image/*) image_preview ;;
  video/*) video_preview ;;
  audio/*) audio_preview ;;
  *) fallback_preview ;;
esac
