#!/usr/bin/env bash

FILE="$1"

function text_preview() {
  bat --paging never --decorations never \
      --color always --theme $COLORSCHEME "$FILE"
}

function pdf_preview() {
  pdftotext "$FILE" -
}

function image_preview() {
  chafa --fill=block --symbols=block "$FILE"
}

function video_preview() {
  mediainfo "$FILE"
}

function audio_preview() {
  mediainfo "$FILE"
}

function fallback_preview() {
  text_preview
}

case "$(file -b --mime-type $FILE)" in
  text/*) text_preview ;;
  */pdf) pdf_preview ;;
  image/*) image_preview ;;
  video/*) video_preview ;;
  audio/*) audio_preview ;;
  *) fallback_preview ;;
esac
