#!/usr/bin/env sh

# Filename:   yabai/yabairc
# Github:     https://github.com/n0ibe/macOS-dotfiles
# Maintainer: Riccardo Mazzarini

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# Floating windows are always on top
yabai -m config window_topmost on

# Tiling options
yabai -m config layout          bsp
yabai -m config top_padding     30
yabai -m config bottom_padding  30
yabai -m config left_padding    30
yabai -m config right_padding   30
yabai -m config window_gap      15

# Border options
yabai -m config window_border               on
yabai -m config window_border_width         3
yabai -m config active_window_border_color  0xffc7c7c7
yabai -m config normal_window_border_color  0xff5c6370

# Rules
yabai -m rule --add app="^Digital Colour Meter$" manage=off sticky=on
yabai -m rule --add title="^fuzzy_opener$" manage=off

# Signals
read -r -d '' destroy_space_if_empty <<- 'EOF'
active_space_index=$(yabai -m query --spaces --space | jq .index)
if $(yabai -m query --windows --space ${active_space_index} | jq 'length == 0'); then
    yabai -m space ${active_space_index} --destroy
fi
EOF

yabai -m signal --add event=window_destroyed action="${destroy_space_if_empty}"
yabai -m signal --add event=application_terminated action="${destroy_space_if_empty}"

# yabai -m signal --add event=window_destroyed action="osascript -e 'display notification \"window_destroyed\"'"
# yabai -m signal --add event=application_terminated action="osascript -e 'display notification \"application_terminated\"'"

# yabai -m signal --add event=window_destroyed action="$destroy_space_if_empty"
# yabai -m signal --add event=application_terminated action="$destroy_space_if_empty"

# read -r -d '' window <<- 'EOF'
# echo "$(yabai -m query --spaces --space | jq .index)" >> ~/windows
# EOF

# yabai -m signal --add event=window_destroyed action="${window}"
# yabai -m signal --add event=application_terminated action="${window}"
