#!/usr/bin/env sh

# Global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  off
yabai -m config window_opacity                  off
yabai -m config window_shadow                   on
yabai -m config auto_balance                    off
yabai -m config mouse_modifier                  ctrl
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# Space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     30
yabai -m config bottom_padding                  30
yabai -m config left_padding                    30
yabai -m config right_padding                   30
yabai -m config window_gap                      15

# Unmanaged programs
yabai -m rule --add app="^Digital Colour Meter$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Keychain Access$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Font Book$" manage=off

yabai -m rule --add title="^fuzzy_opener$" manage=off layer=above opacity=0.8
yabai -m rule --add title="^ndiet$" manage=off layer=above sticky=on

# Sticky programs
yabai -m rule --add app="^Digital Colour Meter$" sticky=on layer=above

# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
limelight &> /dev/null &
