#!/usr/bin/env bash

source "$(dirname $0)"/colorschemes/onedark.sh

yabai -m config window_placement second_child
yabai -m config window_topmost on

yabai -m config window_border              on
yabai -m config window_border_width        4
yabai -m config normal_window_border_color 0xff${normal_window_border_color//#}
yabai -m config active_window_border_color 0xff${active_window_border_color//#}

yabai -m config layout          bsp
yabai -m config external_bar    all:21:0
yabai -m config top_padding     19
yabai -m config bottom_padding  19
yabai -m config left_padding    19
yabai -m config right_padding   19
yabai -m config window_gap      22

yabai -m rule --add app="Digital Colour Meter" manage=off
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Activity Monitor" manage=off
yabai -m rule --add app="Font Book" manage=off
yabai -m rule --add app="App Store" manage=off
yabai -m rule --add app="Logi Options" manage=off

yabai -m rule --add title="floating" manage=off

# https://github.com/koekeishiya/yabai/issues/719#issuecomment-728140216

# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"
