abbr -a bupd "brew update"
abbr -a bupg "brew upgrade"
abbr -a bi "brew install"
abbr -a bu "brew uninstall"
abbr -a bl "brew list"
abbr -a blc "brew list --cask"
abbr -a bstrt "brew services start"
abbr -a bstp "brew services stop"
abbr -a bsr "brew services restart"

abbr -a ipy "ipython"
abbr -a lg "lazygit"

abbr -a psh "peek.py push"
abbr -a pll "peek.py pull"
