abbr -a bci 'brew install --cask'
abbr -a bsr 'brew services restart'
abbr -a cln 'brew cleanup'
abbr -a ipy 'ipython'
abbr -a lg  'lazygit'
abbr -a psh 'peek push'
abbr -a pll 'peek pull'
abbr -a upd 'brew update'
abbr -a upg 'brew upgrade'
