#!/usr/bin/env bash

function notify_add() {
  notify-send \
    --expire-time=5000 \
    --app-name="qutebrowser" \
    --icon="qutebrowser" \
    "Added new torrent" \
    "${QUTE_URL} has started downloading"
}

function torrent_add() {
  transmission-remote --add "${QUTE_URL}"
}

torrent_add && notify_add || true
