#!/run/current-system/sw/bin/bash
#!/usr/bin/env bash

PATH="$PATH:/run/current-system/sw/bin:/home/noib3/.nix-profile/bin"

function notify_done() {
  notify-send \
    --expire-time=5000 \
    --app-name="transmission-remote" \
    --icon="transmission-remote-gtk" \
    "Torrent complete" \
    "${TR_TORRENT_NAME} has finished downloading"
}

function torrent_remove() {
  transmission-remote --torrent "${TR_TORRENT_ID}" --remove
}

notify_done
torrent_remove
