name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: NixOS/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = pipe-operators
      - name: Check formatting
        run: nix run .#check-formatting

  neovim-config:
    name: Neovim config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: NixOS/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = pipe-operators
      - name: Setup Nix cache
        uses: sub60/setup-cache@v0.0.18
        with:
          auth-token: token
      - name: Check the Neovim config
        run: nix run .#check-neovim-config

  nix-lints:
    name: Nix lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: NixOS/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = pipe-operators
      - name: Run Nix linter on all .nix files
        run: nix run .#check-nix-lints

  shell-lints:
    name: shell lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: NixOS/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            experimental-features = pipe-operators
      - name: Run ShellCheck on all .sh files
        run: nix run .#check-shell-lints
