name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.29.2
          nix_conf: |
            experimental-features = pipe-operators
      - name: Check formatting
        run: nix run .#check-formatting

  neovim-config:
    name: Neovim config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.29.2
          nix_conf: |
            accept-flake-config = true
            experimental-features = pipe-operators
      - name: Checkout sub60/cache-action
        uses: actions/checkout@v6
        with:
          repository: sub60/cache-action
          ref: v0.0.5
          ssh-key: ${{ secrets.SUB60_CACHE_ACTION_DEPLOY_TOKEN }}
          path: ./.github/actions/cache-action
      - name: Setup Nix cache
        uses: ./.github/actions/cache-action/js
        with:
          auth-token: ${{ secrets.SUB60_AUTH_TOKEN }}
          github-token: ${{ secrets.SUB60_CACHE_ACTION_RELEASE_ARTIFACT_FETCH_TOKEN }}
      - name: Check the Neovim config
        run: nix run .#check-neovim-config

  nix-lints:
    name: Nix lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.29.2
          nix_conf: |
            accept-flake-config = true
            experimental-features = pipe-operators
      - name: Run Nix linter on all .nix files
        run: nix run .#check-nix-lints

  shell-lints:
    name: Shell lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34
        with:
          nix_version: 2.29.2
          nix_conf: |
            experimental-features = pipe-operators
      - name: Run ShellCheck on all .sh files
        run: nix run .#check-shell-lints
